### ISSUE TITLE
请教一些问题~

### ISSUE THREAD

**Issue by pathbox** [EarlyZhao/id_generator#4]
大概阅读了代码和README, 项目很Rails 哈哈

受到启发，也想到一些问题。

启发： 

>如果每秒的ID消耗在10万，那么建议每个buffer的大小就设置为10万，同时其数量不少于2个为宜，调整buffer大小和数量能适应并发峰值就行
  
当一个buffer消耗完了，需要去update 和select 一次 数据库，极大减少了数据库的压力，相当于每秒可能就一次数据库操作

可以扩展使用到构造uuid的系统中， 有一种获取uuid的方法是会依赖MySQL的自增id，但这样性能瓶颈就会出现在了MySQL insert构造自增id的情况，虽然insert速度也不慢，但相对内存中 ++操作还是天差地别的了
虽然可以用Redis来代替自增id， 但大家冥冥之中觉得Redis的稳定性没有MySQL好，即使redis也有持久化

问题：

- buffer 中的 current 的递增 是否需要原子操作或加锁操作， 毕竟是每秒10w并发的获取id

- 每个数据库中是只存一条配置记录吗？update的时候 不断增量修改这条记录的字段值就行

- 在分布式MySQL设计中，用分片模式，可以讲讲这个模式具体是怎样的？ 我想在想到的是，比如三个MySQL，A B C， 预先给 A 分配范围 0-3000亿的id   B 3000亿- 6000亿  C 6000 -9000亿， 分别先设置好 start_at 值。 这样虽然id没法完全顺序，但是是按照增长的顺序趋势

- 当某个服务中途down了的情况。 比如 A服务 buffer 是10w， current 的值现在增加到了5w， 比如是550000，此时A对应的MySQL中存的记录是上次的更新值end_at 是50000 当取出id为 55000后，这个服务down掉了，  那内存中的550000 值就不在了。 重启这个服务后，current值是多少，如果是去A的MySQL中获取一次值，buffer拿到开始计算的值是50000吗？ 这样又开始计算id的话，就id冲突了， 因为500001-550000 的id在down之前已经使用过了， 不知道是否会遇到这种情况，有解决思路吗，

- 我想到的一个是在启动A服务之前，先手动(或写在脚本中，让其自动化)请求修改A对应的数据库记录，比如增加一个增量值的修改，将start_at加到 560000， 然后在启动服务A， 这样就不会有冲突了，虽然浪费了一些id，但毕竟 down掉的情况是比较少的

**Comment by EarlyZhao** [comment]
感谢你的来信。


从rails开始学起的web，简单借鉴了一下，一下就被你看出来了。
关于你的问题，下面依次是回答，如果说的不清楚再交流哈：
1 current++ 肯定会用互斥锁来保护并发安全
2 每个business_type（某一个业务ID的标示）会对应一条配置记录，update和select都会带上business_type的查询条件，各个business_type的ID消耗和配置都是独立的
3 按照2的回答，分片其实就是用数据库中间件实现根据business_type的分片， 放到不同的库中，同一个business_type只会出现在一个库里面，你说的那种分片方式相对有些复杂。这样可以分散update和select请求，也让单DB宕机不会影响全局，不过是在business_type数量比较多的时候才有价值。
4 服务在启动的时候会加载所有的数据， 然后遍历所有的business_type，依次执行update-select的操作，这和buffer用完了去更新是同一个操作。所以宕机后重启id不会重复，只是有些ID没有被消费就丢掉了。 如果在3里面做了分片的话，在服务启动时需要让中间件将所有库中的数据汇集到一起。

项目还有很多地方不完善，也欢迎你的建议或贡献！




在 2019-03-13 11:07:53，"Cary" <notifications@github.com> 写道：


大概阅读了代码和README, 项目很Rails 哈哈

受到启发，也想到一些问题。

启发：

如果每秒的ID消耗在10万，那么建议每个buffer的大小就设置为10万，同时其数量不少于2个为宜，调整buffer大小和数量能适应并发峰值就行

当一个buffer消耗完了，需要去update 和select 一次 数据库，极大减少了数据库的压力，相当于每秒可能就一次数据库操作

可以扩展使用到构造uuid的系统中， 有一种获取uuid的方法是会依赖MySQL的自增id，但这样性能瓶颈就会出现在了MySQL insert构造自增id的情况，虽然insert速度也不慢，但相对内存中 ++操作还是天差地别的了
虽然可以用Redis来代替自增id， 但大家冥冥之中觉得Redis的稳定性没有MySQL好，即使redis也有持久化

问题：

buffer 中的 current 的递增 是否需要原子操作或加锁操作， 毕竟是每秒10w并发的再获取id

每个数据库中是只存一条配置记录吗？update的时候 不断增量修改这条记录的字段值就行

在分布式MySQL设计中，用分片模式，可以讲讲这个模式具体是怎样的？ 我想在想到的是，比如三个MySQL，A B C， 预先给 A 分配范围 0-3000亿的id B 3000亿- 6000亿 C 6000 -9000亿， 分别先设置好 start_at 值。 这样虽然id没法完全顺序，但是是按照增长的顺序趋势

当某个服务中途down了的情况。 比如 A服务 buffer 是10w， current 的值现在增加到了5w， 比如是550000，此时A对应的MySQL中存的记录是上次的更新值end_at 是50000 当取出id为 55000后，这个服务down掉了， 那内存中的550000 值就不在了。 重启这个服务后，current值是多少，如果是去A的MySQL中获取一次值，buffer拿到开始计算的值是50000吗？ 这样又开始计算id的话，就id冲突了， 因为500001-550000 的id在down之前已经使用过了， 不知道是否会遇到这种情况，有解决思路吗，

我想到的一个是在启动A服务之前，先手动(或写在脚本中，让其自动化)请求修改A对应的数据库记录，比如增加一个增量值的修改，将start_at加到 560000， 然后在启动服务A， 这样就不会有冲突了，虽然浪费了一些id，但毕竟 down掉的情况是比较少的

**Comment by pathbox** [comment]
明白了 business_type ，之前没有看到这个属性

> 4 服务在启动的时候会加载所有的数据， 然后遍历所有的business_type，依次执行update-select的操作 
 也就是 重启的时候会去增量update一次，和我想的解决方案应该是一样的

数据库中间件是使用开源的中间件吗？

要提高性能的话，可行的方向：

- 用比MySQL更快的数据库，比如直换用redis了
- 用更快的http服务(仅讨论golang的)，比如golang 中最快的 fasthttp，在高并发下比原生的http 库 性能好不少
- 内部微服务 提供grpc ，好像你有实现了

**Comment by EarlyZhao** [comment]
> 明白了 business_type ，之前没有看到这个属性
> 
> > 4 服务在启动的时候会加载所有的数据， 然后遍历所有的business_type，依次执行update-select的操作
> > 也就是 重启的时候会去增量update一次，和我想的解决方案应该是一样的
> 
> 数据库中间件是使用开源的中间件吗？
> 
> 要提高性能的话，可行的方向：
> 
> * 用比MySQL更快的数据库，比如直换用redis了
> * 用更快的http服务(仅讨论golang的)，比如golang 中最快的 fasthttp，在高并发下比原生的http 库 性能好不少
> * 内部微服务 提供grpc ，好像你有实现了

如果要对数据分片的话，需要额外引入数据库中间件来做sharding，对项目屏蔽数据分片的细节，这个中间件和这个项目本身没有关联了，项目里面没有提供任何支持。中间件要在`select * from lists` 这种没有business_type条件的情况下，去每个库读数据然后汇集在一起返回。

中间件的选择还是挺多的，mysqlrouter atlas等等都行吧。 

就在启动时加载点数据，不需要redis了，多了复杂性。

你的建议都挺不错，还没了解过fasthttp，我去学习一下。
